packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"


catalog: 
  prettier: 3.4.2
  turbo: 2.3.3
  "@types/node": 22.10.7
  zod: 3.24.1
  tailwindcss: 3.4.17
  postcss: 8.5.1
  typescript: 5.7.3
  "@t3-oss/env-nextjs": 0.11.1
  syncpack: 13.0.0
  eslint: 9.18.0

catalogs: 
  "react-19": 
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.7
    "@types/react-dom": 19.0.3

  "nextjs-15": 
    next: 15.1.3
  "nextjs15-canary":
    next: 15.1.1-canary.25
  
